### ISSUE TITLE
Bundled Urlllib3 is incompatible with python-cryptography in Ubuntu Xenial (16.04 LTS)

### ISSUE THREAD

**Issue by bedaro** [Freso/script.module.requests#21]
I'm 90% sure this addon is causing the problem cited here https://forum.kodi.tv/showthread.php?tid=304613 (at least for me). I am running Ubuntu Xenial and just worked around it by upgrading my system's PyOpenSSL and cryptography; now the error messages no longer appear.

Note the comment in lib/requests/packages/urllib3/contrib/pyopenssl.py saying it requires cryptography >= 1.3.4, but Xenial still has version 1.2.3. Also says it is only tested with PyOpenSSL 16.0.0, but Xenial still has 0.15.1. I'd recommend testing with these earlier versions.

This is the only addon on my system that references PyOpenSSL.

**Comment by beenje** [comment]
1. urllib3 is no longer packaged in this add-on. It was moved to its own add-on (following the official requests library): https://github.com/beenje/script.module.urllib3
2. pyOpenSSL and cryptography are not required to use urllib3 (check urllib3/setup.py). That's why they are not set as dependencies. In the official library they are only installed when you use the [secure] option.
3. If pyOpenSSL and cryptography are installed, urllib3 will indeed try to use them. In case of too old versions present on the system that might cause problems. I found one issue that was fixed: https://github.com/shazow/urllib3/issues/1044
4. I just installed a clean Ubuntu Xenial and kodi in a VM and had no issues because the `python-openssl` package is NOT installed.

If this machine is only used for kodi, remove the `python-openssl` package.
If you need it for something else, I would recommend installing a recent version using pip as mentioned in the kodi forum thread.

You can as well report this problem to the official urllib3 project: https://github.com/shazow/urllib3
Open an issue there and see if they want to improve the dependencies check. 

I just package the official requests/urllib3 libraries for Kodi.
Any fix should be done upstream, so I'll close this issue.
